// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission10_Shaw.Data;

#nullable disable

namespace Mission10_Shaw.Migrations
{
    [DbContext(typeof(BowlingLeagueContext))]
    [Migration("20250405231910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Mission10_Shaw.Data.CollaborativeRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecommendedContentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CollaborativeRecommendations");
                });

            modelBuilder.Entity("Mission10_Shaw.Data.ContentRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecommendedContentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ContentRecommendations");
                });

            modelBuilder.Entity("Mission10_Shaw.Data.SharedArticle", b =>
                {
                    b.Property<long>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar (255)");

                    b.HasKey("ContentId");

                    b.ToTable("SharedArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
